language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - python titanic_predictor/model/prepare.py
    - python titanic_predictor/model/split_train_test.py
    - python titanic_predictor/model/train.py
    - python titanic_predictor/model/evaluate.py
    - pytest