language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - dvc pull
jobs:
    include:
          - stage: Run unit test
            script: pytest
          - stage: Repro
            script: dvc repro pipeline/Dvcfile